# Generate extended LeetCode problems with APL solutions
import json

# Base problems data
base_problems = [
    (16, "3Sum Closest", "最接近的三数之和", "最も近い三つの数の合計", "medium"),
    (17, "Letter Combinations", "电话号码的字母组合", "電話番号の文字の組み合わせ", "medium"),
    (18, "4Sum", "四数之和", "四つの数の合計", "medium"),
    (19, "Remove Nth Node", "删除链表的倒数第N个节点", "リストの末尾から N 番目のノードを削除", "medium"),
    (20, "Valid Parentheses", "有效的括号", "有効な括弧", "easy"),
    (21, "Merge Two Sorted Lists", "合并两个有序链表", "二つのソート済みリストをマージ", "easy"),
    (22, "Generate Parentheses", "括号生成", "括弧の生成", "medium"),
    (23, "Merge k Sorted Lists", "合并K个升序链表", "K 個のソート済みリストをマージ", "hard"),
    (24, "Swap Nodes in Pairs", "两两交换链表中的节点", "ペアでノードを交換", "medium"),
    (26, "Remove Duplicates", "删除有序数组中的重复项", "ソート済み配列から重複を削除", "easy"),
    (27, "Remove Element", "移除元素", "要素を削除", "easy"),
    (28, "Find Index", "找出字符串中第一个匹配项的下标", "文字列内の最初の一致のインデックス", "easy"),
    (31, "Next Permutation", "下一个排列", "次の順列", "medium"),
    (33, "Search in Rotated Array", "搜索旋转排序数组", "回転ソート配列の検索", "medium"),
    (34, "Find First and Last Position", "在排序数组中查找元素的第一个和最后一个位置", "ソート済み配列内の要素の最初と最後の位置", "medium"),
    (35, "Search Insert Position", "搜索插入位置", "挿入位置の検索", "easy"),
    (38, "Count and Say", "外观数列", "外観数列", "medium"),
    (39, "Combination Sum", "组合总和", "組み合わせの合計", "medium"),
    (40, "Combination Sum II", "组合总和 II", "組み合わせの合計 II", "medium"),
    (41, "First Missing Positive", "缺失的第一个正数", "欠落している最初の正の数", "hard"),
    (42, "Trapping Rain Water", "接雨水", "雨水を溜める", "hard"),
    (46, "Permutations", "全排列", "順列", "medium"),
    (48, "Rotate Image", "旋转图像", "画像を回転", "medium"),
    (49, "Group Anagrams", "字母异位词分组", "アナグラムのグループ化", "medium"),
    (50, "Pow(x, n)", "Pow(x, n)", "Pow(x, n)", "medium"),
    (53, "Maximum Subarray", "最大子数组和", "最大部分配列の合計", "medium"),
    (54, "Spiral Matrix", "螺旋矩阵", "スパイラルマトリックス", "medium"),
    (55, "Jump Game", "跳跃游戏", "ジャンプゲーム", "medium"),
    (56, "Merge Intervals", "合并区间", "区間をマージ", "medium"),
    (58, "Length of Last Word", "最后一个单词的长度", "最後の単語の長さ", "easy"),
    (62, "Unique Paths", "不同路径", "ユニークなパス", "medium"),
    (63, "Unique Paths II", "不同路径 II", "ユニークなパス II", "medium"),
    (64, "Minimum Path Sum", "最小路径和", "最小パス合計", "medium"),
    (66, "Plus One", "加一", "プラス 1", "easy"),
    (67, "Add Binary", "二进制求和", "2進数の加算", "easy"),
    (69, "Sqrt(x)", "x 的平方根", "x の平方根", "easy"),
    (70, "Climbing Stairs", "爬楼梯", "階段登り", "easy"),
    (72, "Edit Distance", "编辑距离", "編集距離", "hard"),
    (73, "Set Matrix Zeroes", "矩阵置零", "マトリックスをゼロに設定", "medium"),
    (74, "Search 2D Matrix", "搜索二维矩阵", "2D マトリックスの検索", "medium"),
    (75, "Sort Colors", "颜色分类", "色の並べ替え", "medium"),
    (76, "Minimum Window Substring", "最小覆盖子串", "最小ウィンドウ部分文字列", "hard"),
    (77, "Combinations", "组合", "組み合わせ", "medium"),
    (78, "Subsets", "子集", "サブセット", "medium"),
    (79, "Word Search", "单词搜索", "単語検索", "medium"),
    (80, "Remove Duplicates II", "删除有序数组中的重复项 II", "重複削除 II", "medium"),
    (81, "Search in Rotated Array II", "搜索旋转排序数组 II", "回転ソート配列の検索 II", "medium"),
    (82, "Remove Duplicates from List II", "删除排序链表中的重复元素 II", "リストから重複削除 II", "medium"),
    (83, "Remove Duplicates from List", "删除排序链表中的重复元素", "リストから重複削除", "easy"),
    (84, "Largest Rectangle", "柱状图中最大的矩形", "最大の長方形", "hard"),
    (85, "Maximal Rectangle", "最大矩形", "最大長方形", "hard"),
    (88, "Merge Sorted Array", "合并两个有序数组", "二つのソート済み配列をマージ", "easy"),
    (89, "Gray Code", "格雷编码", "グレイコード", "medium"),
    (90, "Subsets II", "子集 II", "サブセット II", "medium"),
    (91, "Decode Ways", "解码方法", "デコード方法", "medium"),
    (92, "Reverse Linked List II", "反转链表 II", "リンクリストの反転 II", "medium"),
    (93, "Restore IP Addresses", "复原 IP 地址", "IP アドレスの復元", "medium"),
    (94, "Binary Tree Inorder", "二叉树的中序遍历", "二分木の中順走査", "easy"),
    (95, "Unique BST II", "不同的二叉搜索树 II", "ユニークな BST II", "medium"),
    (96, "Unique BST", "不同的二叉搜索树", "ユニークな BST", "medium"),
    (98, "Validate BST", "验证二叉搜索树", "BST の検証", "medium"),
    (99, "Recover BST", "恢复二叉搜索树", "BST の回復", "medium"),
    (100, "Same Tree", "相同的树", "同じ木", "easy"),
    (101, "Symmetric Tree", "对称二叉树", "対称木", "easy"),
    (102, "Level Order Traversal", "二叉树的层序遍历", "レベル順走査", "medium"),
    (104, "Maximum Depth", "二叉树的最大深度", "最大深度", "easy"),
    (105, "Construct Tree", "从前序与中序遍历序列构造二叉树", "木の構築", "medium"),
    (108, "Convert Sorted Array to BST", "将有序数组转换为二叉搜索树", "配列を BST に変換", "easy"),
    (110, "Balanced Binary Tree", "平衡二叉树", "平衡二分木", "easy"),
    (111, "Minimum Depth", "二叉树的最小深度", "最小深度", "easy"),
    (112, "Path Sum", "路径总和", "パス合計", "easy"),
    (113, "Path Sum II", "路径总和 II", "パス合計 II", "medium"),
    (114, "Flatten Binary Tree", "二叉树展开为链表", "木を平坦化", "medium"),
    (118, "Pascal's Triangle", "杨辉三角", "パスカルの三角形", "easy"),
    (119, "Pascal's Triangle II", "杨辉三角 II", "パスカルの三角形 II", "easy"),
    (121, "Best Time to Buy Sell Stock", "买卖股票的最佳时机", "株の売買の最良のタイミング", "easy"),
    (122, "Best Time II", "买卖股票的最佳时机 II", "株の売買 II", "medium"),
    (124, "Binary Tree Max Path Sum", "二叉树中的最大路径和", "最大パス合計", "hard"),
    (125, "Valid Palindrome", "验证回文串", "回文の検証", "easy"),
    (127, "Word Ladder", "单词接龙", "単語のはしご", "hard"),
    (128, "Longest Consecutive", "最长连续序列", "最長連続シーケンス", "medium"),
    (130, "Surrounded Regions", "被围绕的区域", "囲まれた領域", "medium"),
    (131, "Palindrome Partitioning", "分割回文串", "回文分割", "medium"),
    (134, "Gas Station", "加油站", "ガソリンスタンド", "medium"),
    (136, "Single Number", "只出现一次的数字", "一度だけ現れる数字", "easy"),
    (138, "Copy List with Random", "复制带随机指针的链表", "ランダムポインタ付きリストのコピー", "medium"),
    (139, "Word Break", "单词拆分", "単語分割", "medium"),
    (140, "Word Break II", "单词拆分 II", "単語分割 II", "hard"),
    (141, "Linked List Cycle", "环形链表", "循環リンクリスト", "easy"),
    (142, "Linked List Cycle II", "环形链表 II", "循環リンクリスト II", "medium"),
    (143, "Reorder List", "重排链表", "リストの並べ替え", "medium"),
    (144, "Preorder Traversal", "二叉树的前序遍历", "前順走査", "easy"),
    (145, "Postorder Traversal", "二叉树的后序遍历", "後順走査", "easy"),
    (146, "LRU Cache", "LRU 缓存", "LRU キャッシュ", "medium"),
    (148, "Sort List", "排序链表", "リストのソート", "medium"),
    (150, "Evaluate RPN", "逆波兰表达式求值", "逆ポーランド記法の評価", "medium"),
]

print("Generating complete problems database...")
print(f"Total problems to generate: {len(base_problems) + 12}")
